config/routes.rb
Rails.application.routes.draw do
  get 'product_available_areas/index'

  get 'user_accounts/show'

  get 'order/index'

  get 'admin/index'
  get 'product/autocomplete_product_name'

  get 'home/index'
devise_for :users, controllers: { registrations: "registration" }

  resources :product do
    resource :cart_items
      member do
        put :add_category
        put :check_product_for_city
        get :product_avaliability
      end
  end  

  resources :product do
    member do
      post :products_by_category
      post :create_update_related_product
      get :count_additional_images
      get :get_additional_images
    end
  resources :order
  end

resources :order do
  member do
    get :gen_order_invoice
  end
end

resources :cart do
  member do
    put :quantity_update
  end
end
  resources :admin
  resources :user_accounts
  resource :reviews
  resource :products_likes
  resources :shipping_addresses do
    member do
      put :update_selected_address
    end
  end
  
  resources :locations
  resources :pictures 
  resources :hello
  resources :conversations do
    member do
      get :notify_typing_action
    end
    resources :messages
  end

  resources :account_activations, only: [:edit]
  
  root 'product#index'
  post 'product_search' => 'product#search'
  get 'admin_orders_status' => 'order#admin_orders_status'
  post 'admin_order_search' => 'order#search'
  post 'add_product_to_cart' => 'product#addtocart'
  get  'cart_index' => 'cart#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'help' => 'home#help'
  get 'product_filter' => 'product#filter'
  get 'account_close' => 'home#accountclose'
  put 'update_order_status' => 'order#update_order_status'
  put 'remove_image_frm_dir' => 'pictures#remove_image_frm_dir'

  

  get "*path" =>  redirect('/users/sign_up') #new_user_registration_path #("/")

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :order_items
	has_many :order_transactions, dependent: :destroy

	def self.statuses
		{:pending => 1, :delivered => 2, :cancelled=> 3, :unreachable => 4}
	end

	def Order.get_all_placed_orders(current_user)

		@orders_item = Array.new 
		orders = current_user.orders.order("created_at desc")

		orders.each do |order|
			@orders_item.push(OrderItem.get_all_items_of_order(order))

		end
		return @orders_item
	end

	#payment transaction precess
	def Order.pay_now(params, current_user, item_list, credit_card)
		
		require 'paypal-sdk-rest'
		include PayPal::SDK::REST
		PayPal::SDK::REST.set_config(
		  :mode => "sandbox", # "sandbox" or "live"
		  :client_id => "AVO8EAvbySmJk8fDak58e4qeKfFRT28Ylb2g2eq2DVxnDCUhGmRkJ_DbzHXOHvMza-5WbYUGmELQSMf-",
		  :client_secret => "EDpAXhFOHEXEr_SnW5bgfuGQmDuA3sliI6RIMZI3FEd6BcK30L64tVnffchb0GjkeLq0T180t2Onz1yy")
		
		#include PayPal::SDK::REST		
		#PayPal::SDK::Core::Config.load('config/paypal.yml',  ENV['RACK_ENV'] || 'development')
		@payment =Payment.new({
			:intent => "sale",
			:payer => {
				:payment_method => "credit_card",
			    :funding_instruments => [{
			      :credit_card => credit_card }]},
		    :transactions => [{
				   :item_list => {
				      :items => item_list[0] },
				    :amount => {
				      :total => "%.2f" % item_list[1],
				      :currency => "USD" },
				    :description => "This is the payment transaction description." }]      
			})

			if @payment.create
			  @payment     # Payment Id
			else
			  @payment  # Error Hash
			end

		return @payment
	end

	def Order.get_only_order(current_user, order)		
		OrderItem.get_all_items_of_order(order)
	end


	def Order.create_order(current_user)
		@order = current_user.orders.new(:expected_devlivery_on => Date.today + 3.days, :status => "In progress...")
		@order.save
		return @order
	end

	def Order.get_all_pending_orders(option)
		@orders_item = Array.new
		if option == self.statuses[:pending]
			orders = Order.select("orders.*").where(:status=>"In progress...").order("created_at desc")
			orders.each do |order|
				@orders_item.push(OrderItem.get_all_items_of_order(order))
			end
		elsif option == self.statuses[:delivered]
			orders = Order.select("orders.*").where(:status=>"Delivered").order("created_at desc")
			orders.each do |order|
				@orders_item.push(OrderItem.get_all_items_of_order(order))
			end
		elsif option == self.statuses[:cancelled]
			orders = Order.select("orders.*").where(:status=>"Cancelled").order("created_at desc")
			orders.each do |order|
				@orders_item.push(OrderItem.get_all_items_of_order(order))
			end
		else
			orders = Order.select("orders.*").where(:status=>"Unable to delivered").order("created_at desc")
			orders.each do |order|
				@orders_item.push(OrderItem.get_all_items_of_order(order))
			end
		end
		return @orders_item
	end

	# get ids of all matched orders
	def Order.get_orders_id(params) 

		order_id = params[:search].scan(/\d+/).last
		status = ""

		if params[:filter].to_i == self.statuses[:pending]
			status = "In progress..."
		elsif params[:filter].to_i == self.statuses[:delivered]
			status = "Delivered"
		elsif params[:filter].to_i == self.statuses[:cancelled]
			status = "Cancelled"
		else
			status = "Unable to delivered"			
		end

		Order.where('orders.status=? and orders.id = ?',status,order_id).order("created_at desc")

	end

	#return all matched orders
	def Order.get_all_matched_orders(order_ids)
	
		@orders_item = Array.new
		order_ids.each do |order|
			@orders_item.push(OrderItem.get_all_items_of_order(order))
		end				
		return @orders_item
	end

	def Order.update_status(params)
		order = Order.find(params[:order_id])
		if params[:type] == "Delivered" || params[:type] == "Cancelled"
			order.update_attributes(:status => params[:type], :delivery_on => Date.today)
		else
			order.update_attribute("status", "Unable to delivered")
		end
	end

	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :carts, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :product_likes, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy
  has_many :pictures, as: :imageable
  has_many :conversations, :foreign_key => :sender_id
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :fullname, presence:true, length: {maximum: 255}
  validates :phone,   :presence => true,
                     :numericality => true,
                     :length => { :minimum => 10, :maximum => 15 }
  validates :pin,   :presence => true,
                     :numericality => true,
                     :length => {:minimum => 6, :maximum => 6 }
 #  has_attached_file :image, :styles => { :original => "922x922>", :thumb => "220x220>" }, default_url: "/images/:style/missing.png"
 #  validates_presence_of :image
 #  validates_attachment :image, :presence => true,
 # :content_type => { :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] }
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

  before_action :authenticate_user!, only: [:create, :index]
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found_wrong_access
  
  #action to return all orders placed by current logged in user to index view page
  def index
  	@orders = Order.get_all_placed_orders(current_user)
    @order_ids = current_user.orders.order("created_at desc")
  end

# create order using cart id
  def create
    begin    
      @list_items = hash_of_items(params)
      #credit card information
      @credit_card = credit_card(params)
      @response = Order.pay_now(params, current_user, @list_items, @credit_card)
      
      if @response.id.present?
          order = Order.create_order(current_user)
          order_item =nil
        	if(params[:product_id].nil? || params[:product_id].to_i==0)

      	  	cart_item_ids = params[:ids]
            amount_paid = 0;
            total_items = 0;

            if(order.present?)          
              #for sigle or multiple order placed through cart section
        	  	cart_item_ids.each do |c|
        	  		#find cart details
        	  		@cart_item = CartItem.find(c)
                if product_avaliability(@cart_item.quantity,@cart_item.product_id) 
                  
            	  		# call methode to createe order
                    order_item = OrderItem.create_order_item(@cart_item, order)

            	  		if order_item.id.present?

                      amount_paid = amount_paid + (@cart_item.quantity * (Product.find(@cart_item.product_id)).price)
                      total_items =total_items + 1
            	  		  # remove cart item
            	  		  @cart_item.destroy

                    else

                      selected_address = current_user.shipping_addresses.where(isSelected: true).first
                      order.update_attributes(:paid_price => amount_paid, :quantity => total_items,
                                      :delivery_place => selected_address.address_to_ship)
                      #create transaction record after successfull payment
                      OrderTransaction.create_transaction(@response, order.id, amount_paid)
                      flash[:info] = "Their might be some problem. please try again"
                      redirect_to cart_index_path
                    end
                end
              end
            end
      	  else
            #for order placed from home or product details page
      	  	product = Product.find(params[:product_id])
      	  	@cart_item = CartItem.new(product_id: params[:product_id],
        							             quantity: params[:quantity])         

            #check wether user specified quantity available or not
      	  	if (product_avaliability(params[:quantity], params[:product_id]))              

               order_item = OrderItem.create_order_item(@cart_item, order)
               selected_address = current_user.shipping_addresses.where(isSelected: true).first
               order.update_attributes(:paid_price => product.price, :quantity => params[:quantity],
                                        :delivery_place => selected_address.address_to_ship)

               #create transaction record after successfull payment
              OrderTransaction.create_transaction(@response, order.id, product.price)

               respond_to do |format|
                 msg = { :status => "ok", :message => "Success!",:product_id => params[:product_id] }
                       format.json  { render :json => msg } 
                end
              return
            else
              order.destroy
              respond_to do |format|
                 msg = { :status => "ok", :message => "failed",:product_id => params[:product_id] }
                       format.json  { render :json => msg } 
            end
              return
      	    end
          end          
          selected_address = current_user.shipping_addresses.where(isSelected: true).first
          if(total_items>0)
              order.update_attributes(:paid_price => amount_paid, :quantity => total_items,
                                      :delivery_place => selected_address.address_to_ship)
              #create transaction record after successfull payment
              if OrderTransaction.create_transaction(@response, order.id, amount_paid)
              	flash[:success] = "your orders has been placed"
              	redirect_to order_index_path
              end
          else
              order.destroy
              flash[:danger] = "Found some problem in placing order"
              redirect_to cart_index_path
          end
    else
      # failed transaction
      flash[:error] = "Gatway Server problem"
    end
    rescue
      if order
          order.destroy
      end  
      flash[:warning] = "Error #{$!} or Gatway Server connection problem"
      redirect_to cart_index_path
    ensure               
    end
  end

  def update_order_status

    Order.update_status(params)
    render json: { order_id: params[:order_id], status: "success"}

  end

  def admin_orders_status

     option = Order.statuses[:pending]

     if params[:search].present? && params[:filter].present?

          @order_ids = Order.get_orders_id(params) 

          @orders = Order.get_all_matched_orders(@order_ids)

     else
        if params[:filter].present?
            option = params[:filter].to_i

            if option == Order.statuses[:pending]

              @order_ids = Order.where(:status=>"In progress...").order("created_at desc")

            elsif option == Order.statuses[:delivered]

              @order_ids = Order.where(:status=>"Delivered").order("created_at desc")

            elsif option == Order.statuses[:cancelled]
              
              @order_ids = Order.where(:status=>"Cancelled").order("created_at desc")

            else

              @order_ids = Order.where(:status=>"Unable to delivered").order("created_at desc")
            end
          
        end
         @orders = Order.get_all_pending_orders(option)
      
      end

  end

  # print order invoice 
  def gen_order_invoice
    
      @order = Order.find(params[:id])
      @order_items = Order.get_only_order(current_user, @order)

      render json: { order: @order, order_items: @order_items, status: GlobalConstants::SUCCESS }

  end

  private

    def find_all_order_ids

    end

    def product_avaliability(quantity, product_id)

      product = Product.find(product_id)

      orders_items = OrderItem.where(:product_id => product.id)
       orders_no = orders_items.to_a.sum { |e| e.quantity }
    
      if ((product.quantity - orders_no) >= quantity.to_i)
        
          return true
      else
           return false
      end 

    end

    def hash_of_items(params)
      
        @items = []
        @total_amount_to_paid = 0

        if params[:product_id].nil? || params[:product_id].to_i == 0

          cart_ids = params[:ids]

          cart_ids.each do |id|

            cart_item = CartItem.find(id)

            item = Product.find( cart_item.product_id )

            @items.push(:name => item.name,
                  :sku => "SKU" + item.id.to_s,
                  :price => "%.2f" % item.price,
                  :currency => "USD",
                  :quantity => cart_item.quantity.to_s)

            @total_amount_to_paid += cart_item.quantity * item.price

          end

        else

          item = Product.find(params[:product_id])
          
          @items.push(:name => item.name,
                  :sku => "SKU" + item.id.to_s,
                  :price => "%.2f" % item.price,
                  :currency => "USD",
                  :quantity => params[:quantity].to_s)

          @total_amount_to_paid += params[:quantity].to_i * item.price

        end

        return @items, @total_amount_to_paid

    end
      
    def validate_card
      unless credit_card.valid?
        credit_card.errors.full_messages.each do |message|
          errors.add_to_base message
        end
      end
    end
    
    def credit_card(params)
     
      @credit_card ={:type => params[:card_type],
            :number => params[:payee][:card_number],
            :expire_month => params[:date]["card_expires_on(2i)"],
            :expire_year =>  params[:date]["card_expires_on(1i)"],
            :cvv2 => params[:payee][:card_verification],
            :first_name => params[:payee][:first_name],
            :last_name => params[:payee][:last_name],
            :billing_address => {
              :line1 => current_user.street_line1 + "," + current_user.street_line2 ,
              :city => current_user.city,
              :state => current_user.state,
              :postal_code => current_user.pin,
              :country_code => "IN"
            }
        }

      return @credit_card

    end
  
end

app/helpers/order_helper.rb
module OrderHelper
	def return_class_on_status(order)
		if order.status == "Delivered"
			"order-details-delivered"
		elsif order.status == "In progress..."
			"order-details-processing"
		elsif order.status == "Cancelled"
			"order-details-cancelled"
		else
			"order-details-unreachable"
		end
			
	end
end

app/views/order/_admin_orders_status.js.erb
$("#id_all_orders_status").html( $("<%= escape_javascript(render @bind_orders) %>"));

app/views/order/_bind_orders.html.erb
<% if(@orders.length > 0) %>
		<table>

<% @orders.each_with_index do |order,i| %>
		<tr class="<%= return_class_on_status(@order_ids[i]) %>", title="<%= @order_ids[i].status %>", id="parent_row_<%= @order_ids[i].id %>"><td>
			<div>ORDER-ID: ORD#<%= @order_ids[i].id %></div>
			<div>CREATED ON: <%= order[0].created_at.to_time.strftime('%B %e at %l:%M %p') %></div>
			<div> Rs. <%= order.to_a.sum { |e| e.total_price }%>
			<img src="/assets/down_arrow_circle.png", alt="down", class="up-down-img", id="arrow_<%= @order_ids[i].id %>" />
			</div>
		</td>
		</tr>
			<tr id="child_row_<%= @order_ids[i].id %>">			
				<td>
				<div style="display:none;", id="section_<%= @order_ids[i].id %>" >
					<table>
					<% order.each_with_index do |item,j| %>
						<tr>
						<td><%= (j+1) %></td>
							<td>
							<%= link_to image_tag("products/"+item.image,alt: "image"),product_path(item)%></td>			
							<td><%=link_to item[:name], product_path(item[:product_id]) %></td>
							<td>Rs.<%= item[:total_price] %></td>
							<td><%= item[:quantity]%></td>
						</tr>
					<% end %>
					</table>
					<div class="order-status-section">
						<table>
							<tr>
								<td>Expected on : <span><%= order[0].expected_devlivery_on.to_time.strftime('%B %e at %l:%M %p') %></span> </td>
								<td>Delivered on : <span><%= order[0].delivery_on %> </span> </td>
								<td>Status : <span><%= order[0].status %> </span></td>
							</tr>
							<tr>
								<td>Delivering address : </td>
								<td colspan="2"><%= order[0].delivery_place %></td>
							</tr>
							<% if order[0].status == "In progress..." %>
							<tr>
								<td colspan="3"> 
									<%= link_to "Delivered", "#", class: "btn btn-primary btn-order-status-delivered", id: "btn_delivered_#{ @order_ids[i].id }" %>
									<%= link_to "Unreachable", "#", class: "btn btn-primary btn-order-status-unreachable", id: "btn_unreachable_#{ @order_ids[i].id }" %>
								</td>
							</tr>
							<% end %>
						</table>
					</div>
				</div>
				</td>
			</tr>
	<% end %>		
	</table>				
		<% else %>
	 <div>
	 	<div class="empty-products">No order placed</div>
	 	
	 </div>
	<% end %>

app/views/order/admin_orders_status.html.erb
<% provide(:title, "maintain order status") %>
<h2>Manage orders</h2>
<div class="order-main-section">
	<div class="row">
		<%= form_for(admin_orders_status_path,method: 'get') do  %>
			<div class="col-md-5">
			<%= select_tag "filter", options_for_select( [["Pending","1"],["Delivered", "2"],["Cancelled order", "3"], ["Un-reachable orders","4"]], params[:filter]), class: 'order_status', :onchange => "this.form.submit()" %>	
			</div>
			<div class="col-md-2"></div>
			<div class="col-md-5 order-search ">
			<%= text_field_tag 'search', params[:search], placeholder: 'Search by order id...', class: "form-control" %>
			<%= submit_tag "Search", class: "btn btn-primary" %>
		</div>
	<% end %>
	</div>
<%= render 'bind_orders' %>

app/views/order/index.html.erb
<h1>Your orders summary</h1>
<div class="order-main-section">

<% if(@orders.length > 0) %>
		<table>

<% @orders.each_with_index do |order,i| %>
		<tr class="<%= return_class_on_status(@order_ids[i]) %>", title="<%= @order_ids[i].status %>", id="parent_row_<%= @order_ids[i].id %>"><td>
			<div>ORDER-ID: ORD#<%= @order_ids[i].id %></div>
			<div>CREATED ON: <%= order[0].created_at.to_time.strftime('%B %e at %l:%M %p') %></div>
			<div> Rs. <%= order.to_a.sum { |e| e.total_price }%>
			<img src="/assets/down_arrow_circle.png", alt="down", class="up-down-img", id="arrow_<%= @order_ids[i].id %>" />
			</div>
		</td>
		</tr>
			<tr>
			
				<td>
				<div style="display:none;", id="section_<%= @order_ids[i].id %>" >
					<table>
					<% order.each_with_index do |item,j| %>
						<tr>
						<td><%= (j+1) %></td>
							<td>
							<%= link_to image_tag("products/"+item.image,alt: "image"),product_path(item)%></td>			
							<td><%=link_to item[:name], product_path(item[:product_id]) %></td>
							<td>Rs.<%= item[:total_price] %></td>
							<td><%= item[:quantity]%></td>
						</tr>
					<% end %>
					</table>
					<div class="order-status-section">
						<table>
							<tr>
								<td>Expected on : <span><%= order[0].expected_devlivery_on.to_time.strftime('%B %e at %l:%M %p') %></span> </td>
								<td>Delivered on : <span><%= order[0].delivery_on %> </span> </td>
								<td>Status : <span id="spn_show_order_status_<%=@order_ids[i].id %>"><%= order[0].status %> </span></td>
							</tr>
							<tr>
								<td>Delivered address : </td>
								<td colspan="2"><%= order[0].delivery_place %></td>
							</tr>
							<tr>
								<td colspan="3"> 

									<% if order[0].status == "In progress..." %>
										<%= link_to "Cancel", "#", class: "btn btn-primary btn-order-status-cancelled", id: "btn_cancelled_#{ @order_ids[i].id }" %>
									<% end %>
									<% if order[0].status == "Delivered" %>
										<%= link_to "Print invoice","#", id: "link_gen_order_invoice_#{ @order_ids[i].id }" , class: "btn btn-primary link-order-invoice-gen", style: "float:right;" %>
									<% end %>
								</td>
							</tr>
							
						</table>
					</div>
				</div>
				</td>
			</tr>
		
	<% end %>
		
	</table>
				
	<% else %>
	 <div>
	 	<div class="empty-products">No order placed</div>
	 	
	 </div>
	<% end %>
<div><%= link_to "Continue shopping",product_index_path, class: "btn btn-primary" %>
	 	<%= link_to "Go to cart",cart_index_path(:product_id => 0), class: "btn btn-primary" %>

	 	 </div>
	</div>