config/routes.rb
Rails.application.routes.draw do
  get 'product_available_areas/index'

  get 'user_accounts/show'

  get 'order/index'

  get 'admin/index'
  get 'product/autocomplete_product_name'

  get 'home/index'
devise_for :users, controllers: { registrations: "registration" }

  resources :product do
    resource :cart_items
      member do
        put :add_category
        put :check_product_for_city
        get :product_avaliability
      end
  end  

  resources :product do
    member do
      post :products_by_category
      post :create_update_related_product
      get :count_additional_images
      get :get_additional_images
    end
  resources :order
  end

resources :order do
  member do
    get :gen_order_invoice
  end
end

resources :cart do
  member do
    put :quantity_update
  end
end
  resources :admin
  resources :user_accounts
  resource :reviews
  resource :products_likes
  resources :shipping_addresses do
    member do
      put :update_selected_address
    end
  end
  
  resources :locations
  resources :pictures 
  resources :hello
  resources :conversations do
    member do
      get :notify_typing_action
    end
    resources :messages
  end

  resources :account_activations, only: [:edit]
  
  root 'product#index'
  post 'product_search' => 'product#search'
  get 'admin_orders_status' => 'order#admin_orders_status'
  post 'admin_order_search' => 'order#search'
  post 'add_product_to_cart' => 'product#addtocart'
  get  'cart_index' => 'cart#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'help' => 'home#help'
  get 'product_filter' => 'product#filter'
  get 'account_close' => 'home#accountclose'
  put 'update_order_status' => 'order#update_order_status'
  put 'remove_image_frm_dir' => 'pictures#remove_image_frm_dir'

  

  get "*path" =>  redirect('/users/sign_up') #new_user_registration_path #("/")

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :cart_items
	has_many :reviews, dependent: :destroy
	belongs_to :products_like
	has_one :related_product
	has_many :pictures, as: :imageable
	has_and_belongs_to_many :locations
	validates_presence_of :product_type_id, message: "Select category"
	validates :name, :presence =>true
	validates :price, :presence => true, :numericality => true
	validates :image, :presence => true
	validates :description, :presence => true
	validates :quantity, :presence => true, :numericality => {:only_integer => true}

	# has_attached_file :image, :styles => { :original => "922x922>", :thumb => "220x220>" }, default_url: "/images/:style/missing.png"
 #  	validates_presence_of :image
 #  	validates_attachment :image, :presence => true,
 # 						 :content_type => { :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] }
	
	#get all products of specific category type

	def Product.get_all_products_by_types(params)
		Product.all.where("product_type_id = #{params[:type_id]}")	
	end

	#get product on product category selection basis
	def Product.filter_product(selected_category)
		unless selected_category.nil?
			@products = Product.where(:product_type_id => selected_category).order("created_at desc")

		end
	end

	#get all name matched products 
	def Product.get_searched_product(params)

		if params[:search].nil?
      		Product.all.order("created_at desc")
      	else
      		Product.where('name LIKE ?', "%#{params[:search]}%")
                             .order("created_at desc")
      	end
	end

	#return all reviews given by users for selected product
	def Product.get_reviews_for_a_product(params)

		Review.joins("left join users on reviews.user_id= users.id")
            .where("reviews.product_id=?",params[:id])            
            .select("reviews.*,users.id,users.fullname")            
            .order("reviews.created_at desc")
            
	end

	def Product.get_all_related_products_details(str_related_products)
		temp_ids = str_related_products.split(",").map(&:to_i)
		
		Product.where("id in (?)",temp_ids)
	end
end

app/models/products_type.rb
class ProductsType < ActiveRecord::Base


end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  #check user authetication to restrict user 
  #to create , edit and update a product
  before_action :authenticate_user!, only: [:new, :edit,:create, :update]
  #check wether user is in admin role or not to restrict some functionality
  before_action :check_for_admin, only: [:new, :edit,:create, :update]

  #interface to create new product
  def new
  	@product = Product.new
    #retrive product categories
  	get_product_type
  end

  #action to return products
  def index
    get_product_type
    @product = Product.new

    #check wether any category selected or not
    if(params[:filter].nil? || params[:filter].blank? )
         # get products with search or without search 
         @products = Product.get_searched_product(params)
                                 .paginate(:page => params[:page], :per_page => 16)    	

    #checking if selected category is exists or not
    elsif ProductsType.exists?(:id => params[:filter])      
      @products = filter.paginate(:page => params[:page], :per_page => 16)
    else
      flash[:info] = "Product category doesn't exists"
      redirect_to product_index_path
    end

  end

  #action to return details of one product to view
  def show

  	@product = Product.find(params[:id])
    if @product.isVisible_to_user || current_user.isAdmin

      #get all reviews given by users for selected product
      @reviews = Product.get_reviews_for_a_product(params)

      #get all products related to current selected product
      obj_related_products = RelatedProduct.get_all_related_products(@product.id)

      if (!obj_related_products.nil?)

        str_related_products = obj_related_products.related_products

        @related_products = Product.get_all_related_products_details( str_related_products )
        
      else
        @related_products = obj_related_products
      end

      directory =GlobalConstants::PRODUCT_ADDITIONAL_IMAGE_PATH + @product.id.to_s

      @additional_product_images = nil

      if Dir.exists?(directory)
        @additional_product_images = Dir.foreach(directory ).
                                      select{ |x| File.file?("#{GlobalConstants::PRODUCT_ADDITIONAL_IMAGE_PATH + @product.id.to_s}/#{x}")}

      end
    else
      flash[:danger]="Product does not exist"
      redirect_to root_path
    end
    
    rescue ActiveRecord::RecordNotFound => e
    flash[:warning] = "Sorry product not found !"
    redirect_to root_path

  end


  def edit
  	get_product_type
  	@product = Product.find(params[:id])

  end

  #action to search a product 
  #here this method redirect to index action where search product will  return
  def search
  	redirect_to product_index_path(:search => params[:search])
  end

  #create new product
  def create

    get_product_type
    @product = Product.new(product_params) 
    @product.likes=0
    @product.unlikes=0
    # if image is selected then save the image
    if (!params[:product][:image].nil?)
      uploaded_io = params[:product][:image]
      #method to save image file
      save_image(uploaded_io)   	
      #update the current product instace image variable data
      @product.image = (( Product.last.present? ? Product.last.id : 0) + 1).to_s+"_"+uploaded_io.original_filename
    end    
    #insert new product into database server
    if @product.save
      Picture.create_new(@product)
      create_products_location_relation(@product)
    	flash[:success] = "Product added successfully"  	
    	redirect_to product_index_path

    elsif @product.errors.count>0
        render "new"
      else
      	flash[:danger] = "failed to save"
      	redirect_to new_product_path
    end

  end

  #action to update a product 
  def update
    @product = Product.find(params[:id])
    #block to delete image if another image is seleted to replace the existing one
    if (params[:product][:image] && !@product.image.nil? && (File.exist?(Rails.root.join('app/assets/images', 'products', @product.image))))
            File.delete(Rails.root.join(image_path, 'products', @product.image))
    end
    #block to update product details
    if @product.update_attributes(product_params)
      #update selected cities
      create_products_location_relation(@product)
      if( !params[:product][:image].nil? )          
          uploaded_io = params[:product][:image]
          #save new image
          save_image(uploaded_io)
          #update image name
          @product.update_attribute(:image, (Product.last.id+1).to_s+"_"+uploaded_io.original_filename)          
      end
      flash[:success] = "updated successfully"
      redirect_to product_path
    else

      flash[:danger] = "failed to update"
      redirect_to edit_product_path(@product)
    end

  end

   #related product of a product 
   def products_by_category
     @products = Product.get_all_products_by_types(params)
     @related_products = RelatedProduct.find_by(:product_id=>params[:id])
     render json: {:products => @products, :related_products => @related_products}
   end
   
  #return all product categories
  def get_product_type
  	@ProductsType = ProductsType.all.order(:name)
  end

  #method to create new category
  def add_category

    @product_type = ProductsType.new(:name => params[:cat_name])
    @product_type.save
    render json: {:product_type => @product_type}

  end

  #create related product record if not exist or update
  def create_update_related_product

     if(RelatedProduct.create_update_related_product(params))
      render json: {:id =>params[:id], :status => "success"}
     end
  end

  #check wether seleted city is deliverable or not
  def check_product_for_city
    @selected_cities = Product.select("area_to_available")
                  .where("id=#{params[:product_id]}")[0]

    unless @selected_cities.area_to_available.nil?
      if @selected_cities.area_to_available.downcase.split(",").include?(params[:city].downcase)
        render json: {:status => "available"}
      else
        render json: {:status => "unavailable"}
      end
    else
      render json: {:status => "unavailable"}
    end
    
  end

def count_additional_images
    images_count = Dir[GlobalConstants::PRODUCT_ADDITIONAL_IMAGE_PATH + params[:id].to_s+"/**/*"].count { |file| File.file?(file) }    
    render json: { :status => GlobalConstants::SUCCESS ,:images_count => images_count}
end

def get_additional_images
  
    directory =GlobalConstants::PRODUCT_ADDITIONAL_IMAGE_PATH + params[:id].to_s
    @additional_product_images = nil
    if Dir.exists?(directory)
      @additional_product_images = Dir.foreach(directory ).
                                    select{ |x| File.file?("#{GlobalConstants::PRODUCT_ADDITIONAL_IMAGE_PATH + params[:id].to_s}/#{x}")}
    end
    render json: { :status => GlobalConstants::SUCCESS, :image_name => @additional_product_images, :product_id => params[:id] }
end

#all the private method start from here
private 
  
  def create_products_location_relation(product)    
    product.locations.destroy_all
    unless params[:selected_cities].nil?
        params[:selected_cities].each do |city_id|
        city = Location.find(city_id.to_i)
        product.locations << city
     end
    end
  end

  #save selected image
  def save_image(uploaded_io)
    #file open
    File.open(Rails.root.join(image_path, 'products', 
              ( (Product.last.present? ? Product.last.id : 0 ) + 1 ).to_s+"_"+uploaded_io.original_filename), 'wb') do |file|    
    #write coverted bytes to file
    file.write(uploaded_io.read)
    end  
  end

  #all the fields to restricted to access 
	def product_params
    puts params
		params.require(:product).permit(:name, 
                                    :image,
                                    :area_to_available, 
                                    :product_type_id,
                                    :price, 
                                    :description, 
                                    :isVisible_to_user,
                                    :quantity)
	end

  #returns current user role
	def check_for_admin
		unless current_user.isAdmin? 
			flash[:warning] = "Access denied"	
			redirect_to root_path
		end
	end

  # filter the product as per selection
  def filter
    Product.filter_product(params[:filter])
  end
end

app/helpers/product_helper.rb
module ProductHelper
	def isLiked(product_id)
		ProductLike.exists?(:product_id => product_id, :user_id => current_user.id, :like => 1)
	end
	def isUnliked(product_id)
		ProductLike.exists?(:product_id => product_id, :user_id => current_user.id, :like => 0)
	end
	def product_avalabiliity(product_id)
		product = Product.find(product_id)
		orders_items = OrderItem.where(:product_id => product_id)
		orders_no = orders_items.to_a.sum { |e| e.quantity }
		
		product.quantity - orders_no
		

	end
	def get_selected_cities(product_id)

		product = Product.find(product_id)
		@selected_cities = 	product.locations.pluck(:name)	
		
	end
end

app/views/product/_additional_images.html.erb
<!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Add additional images</h4>
        </div>
        <div class="modal-body" style="padding:40px 50px;">
          <% if @additional_product_images.present? %>
            <div class="div-additional-image">
              <ul>
              <% @additional_product_images.each do |image| %>
                <li>
                  <img src="<%= "/assets/products/additional_images/" + @product.id.to_s + "/" + image %>", alt="image", id="additional_img_<%= @product.id.to_s %>" />
                  <a href="#", id="del_<%= @product.id.to_s + "_" + image %>", class="del-additional-img">x</a>
                </li>
              <% end %>
              </ul>
            </div>
            <% end %>
          <%= form_for(:picture, url: pictures_path(:product_id => @product.id), method: "post", html: { id: "picture_form" }) do |f| %>
            <div class="form-group">
            <span id="spn_error_display", style="display:none; color:red;"></span>
              <%= f.file_field :image, id: "additional_image", class: "form-control" %>
            </div>
            
              <a href="#", class = "btn btn-success btn-block lnk-add-additional-images", id="lnk_additional_images_<%= @product.id.to_s %>">Add</a>
          <% end %>
        </div>
        <div class="modal-footer">
         
        </div>
      </div>
      
    </div>
  </div> 
</div>

app/views/product/_change_address.html.erb
<div class="shipping-adress">
	<div>Shipping address <a href="#",value="Change",id="btn_change_address" class="btn btn-primary"></a> </div>
	<div>
		<textarea id="<%= address_<%= current_user.id %>" ></textarea>
	</div>
	<div>
		<a href="#",id="CheckOut", class="btn btn-primary"></a>
	</div>
</div>

app/views/product/_related.html.erb
<% if @related_products && @related_products.length >0 %>
	<div id="slider_main_section">
			<% @related_products.each do |item| %>

			<div id="wrapper">
				<div id="slider">
					<%= link_to image_tag("products/"+item.image, title: item.name), product_path(item) %>
					<span><%= item.name[0..10]+"..." %></span>
					<span>Rs. <%=item.price %></span>
				</div>
			</div>
			<% end %>
		
	</div>
<%else %>
 No related products found
<%end %>

app/views/product/_review.html.erb
<div>
	<span>Comment on above product</span>
	<%= text_area(:comment, :text, size: "50x5",class: "form-control", placeholder: "Enter your comment") %>
		<%= link_to "Add comment", "#", id: "comment_#{@product.id}", class: "comment_link btn btn-primary" %>
	</div>
	<div class="comments-display-section">
	<% if @reviews.length>0 %>
	 <% @reviews.each do |review| %>
			<div class="comments_each">
				<div>
					<span>On <%=review.created_at.to_formatted_s(:long_ordinal) %> </span> by <%= link_to review.fullname,user_account_path(review.user_id) %>
				</div>
				<div class="comments-text">
					<%= review.comment %>
				</div>
				
			</div>
	 <% end %>
	<% else %>
		You will be first to comment
	<% end %>
	</div>

app/views/product/_shipping_address.html.erb
<div id="address_overlay", style="display:none;"></div>

<div id="address_detail_section_<%= user_signed_in? ? current_user.id : "0" %>", class="address-section" style="display:none;">
<div class="address-header"><div>Shipping Addresses </div><a href="#", class="btn btn-primary" >Add new</a></div>
	<% if (user_signed_in?) %>
		<div class="address-each-section">
			<% for address in shipping_addresses %>
				<div>
					<%= radio_button_tag 'shipping_address', address.id, address.isSelected %>
					<span><%= address.address_to_ship %></span>
					<%= link_to image_tag("delete-icon.png",alt: "image",title: "remove", class: "remove-address", id: "remove_#{address.id}"),"#" %> 
					
				</div>
			<% end %>
		</div>
	<% end %>
	<div >
	<textarea id="txt_area_new_address", placeholder="Add new address", rows="6" style="display:none;"></textarea> </div>
	<div class="div-check-out">
		<a href="#", class="btn btn-primary", id="link_product_check_out" > Check out</a>
		<a href="#", id="btn_close" >Close</a>
	</div>
</div>

app/views/product/edit.html.erb
<% provide(:title,@product.name) %>
<h1>Update product</h1><div class="row">
	<div class="col-md-6 col-md-offset-3">
			<%= form_for(@product, url: product_path(@product)) do |f| %>
			<div class="field">
				<%= f.label :product_type_id, "Category :" %>			
				<%= errors_for @product, :product_type_id %>
				<%= f.collection_select :product_type_id, @ProductsType, :id, :name, include_blank: "Select category", class: "form-control" %>
			</div>
			<div class="field">
				<%= f.label :name, "Name :" %>
				<%= errors_for @product, :name %>
				<%= f.text_field :name, class: "form-control" %>
			</div>
			<div class="field">
				<%= f.label :price, "Price :" %>			
				<%= errors_for @product, :price %>
				<%= f.text_field :price, class: "form-control" %>
			</div>
			<div class="field">			
				<%= f.label :quantity, "Quantity :" %>
				<%= errors_for @product, :quantity %>
				<%= f.text_field :quantity, class: "form-control",placeholder: "Enter quantity", value: @product.quantity %>
			</div>
			<div class="field">	
				<%= image_tag("products/"+@product[:image].to_s,alt: "image",title: @product[:description]) %>
				
				<%= f.file_field :image%>
				
			</div>
			<div class="field">
			<%= @selected_cities =  get_selected_cities(@product.id) %>
				<span>( Select cities or it will assume to all )</span> 
				<select id:"available_cities" name="selected_cities[]" multiple="multiple", class="form-control">
					<% $cities.each do |c| %>
    				 <option value="<%= c.id %>", <%= @selected_cities.include?(c.name) ? 
						"selected=selected" : '' %> ><%= c.name %></option>
					<% end %>
				</select>
			</div>
			<div class="field">
				<%= f.label :description, "Description :" %>
				<%= errors_for @product, :description %>
				<%= f.text_area :description, size: "50*10", class: "ckeditor" ,:ckeditor => {:language => 'uk'}%>
			</div>
			<div class="field remember-me">
				<%= f.label :isVisible_to_user, class: "checkbox inline checkbox-label" do %>
				<%= f.check_box :isVisible_to_user %>
				<span>Visible to user ?</span>
			</div>
		<% end %>
			<% if @product.present? %>
				<%= f.submit "Update", class: "btn btn-primary" %>
			<% else%>
			<%= f.submit "Add", class: "btn btn-primary" %>
		<% end %>

<% end%>
	</div>
</div>

app/views/product/index.html.erb
<% provide(:title,"home page") %>
<%= form_for(product_index_path,method: 'get') do  %>
	<%= select_tag "filter", 
	options_for_select(@ProductsType.collect{|pt| [pt.name,pt.id]}, params[:filter]),:include_blank => 'Select category', class: 'my_filter',:onchange => "this.form.submit()" %>
	<% if( user_signed_in? && current_user.isAdmin? ) %>
		<%= link_to "Add product", new_product_path, 'data-no-turbolink' => true, class: "btn btn-primary add-mew-product" %>
	<% end %>
	
<% end %>
<ul class="users">
<% if (@products.select{|product| product.isVisible_to_user==true}.length >0 ) %>
	<% @products.each do |product| %>
	<%= form_for(:cart,url: product_cart_items_path(product)) do |f| %>
		<% if (product[:isVisible_to_user] || (user_signed_in? && current_user.isAdmin?)) %>
			<li>

				<a class="vlightbox2"><%=  image_tag("products/"+product.image,alt: "image",id: "image_#{product.id}",class: "img-zoom") %>
				<% id = "vlb_zoom_#{product.id}" -%>
				<div id="<%= id -%>", class="vlb_zoom" style="position: absolute; display: none;"></div></a>
				<div><%= link_to product.name[0..21]+"...", product, title: product.name %></div>
				<div>Rs. <%= product.price %></div>
				<% if product_avalabiliity(product.id) > 0 %>
					<div class="product-quantity">QTY: <%= f.text_field :quantity, value: 1, id: "product_quantity_#{product.id}", class: "txt-product-quantity" %>
				
					<span id="product_in_stoke_<%= product.id %>", style="display:none;"><%= product_avalabiliity(product.id).to_s %> </span></div>
					<div class="add-cart-link"><%= f.submit 'Add to cart',class: "btn btn-primary" %></div>
					<div class="add-cart-link"><%= link_to 'Place order',"#",class: "btn btn-primary link-place-order", id: "placeorder_#{product.id}" %></div>
				<% else %>
					<div style="padding-bottom:16px;">
					<span id="product_in_stoke_<%= product.id %>", style="color:red;">Out of stoke </span></div>
					<div class="add-cart-link"><%= f.submit 'Add to cart',class: "btn btn-primary" , disabled: "disabled" %></div>
					<div class="add-cart-link"><%= link_to 'Place order',"#",class: "btn btn-primary link-place-order", id: "placeorder_#{product.id}" , disabled: "disabled" %></div>
				<% end %>
				</li>
		<% end %>
	<% end %>
	<% end %>
<% else %>
	<div class="empty-products">OOPS! Products not found </div>
<%end%>
</ul>
<div class="overlay" style="display:none;"></div>
	<div class="show-category-panel order-placed" style="display:none;">
		<div><span>Your order has been placed</span></div>
		<div><%= link_to "OK",product_order_index_path(:product_id=>0)%>
		</div>
	</div>
<div class="image-large-div show-category-panel", style="display:none;">
<%= image_tag("close.png",alt: "close",title: "close",id: "close_btn") %>
	
	<div>
		<img class="image-large", alt="image">
		<div class="div-additional-image image-shw-in-vertical">
      
		</div>
	</div>
	
</div>
<%= will_paginate @products %>
<%= render "layouts/shipping_address" %>

app/views/product/show.html.erb
<% provide(:title,@product.name) %>
<%= form_for(:cart,url:product_cart_items_path(@product),method: "post", html: { id: "product_form" }) do |f| %>
	<h3> <%= f.label @product.name %> </h3>
	<hr/>
	<div>
		<div class="admin-usable-link">
			<% if (user_signed_in? && current_user.isAdmin?) %>
				<%= link_to "Edit product", edit_product_path(@product),'data-no-turbolink' => true %>
			
				<%= link_to "Add related products", "#", class: "related-products-popup", id: "products_type_#{@product.product_type_id}_#{@product.id}" %>
				<a href="#", id="myBtn">Add additional images</a>
				
				<% end %>
		</div>
		<div class="product-details">
		
			<div class="main-images-with-additiinal">
				<div>
					<%= image_tag("products/"+@product.image.to_s,alt: "image",title: @product.name, id: "product_main_image") %>
				</div>
				<% if @additional_product_images.present? %>

				<div class="div-additional-image">
	              <ul>

	              <% @additional_product_images.each do |image| %>

	                <li>
	                  <img src="<%= "/assets/products/additional_images/" + @product.id.to_s + "/" + image %>", alt="image", class="img-show-in-large" />	                  
	                </li>

	              <% end %>

	              </ul>

            	</div>
            	
            	<% end %>
			</div>
			<div class="product-add-cart">
				<div >Price : Rs. <span><%= @product.price.to_s %> </span></div>
				<% if product_avalabiliity(@product.id) > 0 %>
					<div class="product-quantity">QTY: <%= f.text_field :quantity, value: 1, id: "product_quantity_#{@product.id}", class: "txt-product-quantity" %>

					<div >In stoke: <span id="product_in_stoke_<%= @product.id %>"><%= product_avalabiliity(@product.id).to_s %> </span></div>	
					</div>
					<div class="div-check-avail">
						<input type="text", value="<%= user_signed_in? ? current_user.city : "" %>", id="txt_product_avail", placeholder="Check by city", class="form-control"/> 

						<input type="button", value="Check", class="btn-product-availability", id="btn_chk_avail_<%= @product.id %>"/> 

						<% if user_signed_in? %>
							<% if get_selected_cities(@product.id).include?(current_user.city) %>
								<% @visibility = "block" 
								 @not_visible ="none" %>
							<% else %>
								<% @visibility = "none" 
								@not_visible ="block" %>
							<% end %>
						<% else %>
							<% @not_visible ="none" 
							 @visibility = "none" %>
						<% end %>

							<span id="span_avail", style="display:<%= @visibility %>;color:green;float: left;font-size: 12px;">Product is available for above city</span>
							
							<span id="span_not_avail", style="color:red;float: left;font-size: 12px;display:<%= @not_visible %>;">Product is not available for above city</span>
						
					</div>
					<div class="add-cart-link">
					<%= f.submit 'Add to cart',class: "btn btn-primary" %></div>
					<div class="add-cart-link"><%= link_to 'Place order',"#",class: "btn btn-primary link-place-order", id: "placeorder_#{@product.id}" %></div>
				<% else %>
					<div class="product-quantity">
						QTY: <%= f.text_field :quantity, value: 0, id: "product_quantity_#{@product.id}", class: "txt-product-quantity", disabled: "disabled" %>
						<div >
							<span id="product_in_stoke_<%= @product.id %>", style="color:red;">Out of stoke </span>
						</div>	
					</div>
					<div class="add-cart-link">
						<%= f.submit 'Add to cart',class: "btn btn-primary" , disabled: "disabled"%></div>
					<div class="add-cart-link">
						<%= link_to 'Place order',"#",class: "btn btn-primary link-place-order", id: "placeorder_#{@product.id}", disabled: "disabled" %></div>
				<% end %>

				<div class="like-unlike-section">
					<div>
						<% if user_signed_in? && isLiked(@product.id) %>
							<img src="/assets/right.png", value="Like", class="liked-btn"  />
						<% elsif user_signed_in? && isUnliked(@product.id) %>
							<img src="/assets/like.png", id="like_<%=@product.id %>", value="Like", class="liked-btn",  />
						<% else %>
							<img src="/assets/like.png", id="like_<%=@product.id %>", value="Like", class="like-btn",  />
						<% end %>
							<span id
							="like_span"><%= @product.likes %> likes</span>
					</div>
					<div>
					<% if user_signed_in? && isUnliked(@product.id) %>
						<img src="/assets/right.png", id="unliked_<%=@product.id %>", value="Unlike", class="unliked-btn"  />
					<% elsif user_signed_in? && isLiked(@product.id) %>
						<img src="/assets/dislike.png", id="unlike_<%=@product.id %>", value="Unlike", class="unliked-btn" />
					<% else %>
						<img src="/assets/dislike.png", id="unlike_<%=@product.id %>", value="Unlike", class="unlike-btn" />
					<% end %>
						<span id="unlike_span"><%=@product.unlikes %> unlikes</span>
					</div>
				</div>
			</div>
		</div>
		<div class="related-products-main-div">
		<div class="header">Recommended products</div>

			<div class="related-products">
				<%= render 'related' %>
			</div>
		</div>
		
		<div class="product-description">
			<div class="description_header">Description :</div>
			<div class="description_details"><%= @product[:description].html_safe %></div>
		</div>
		
	</div>
<% end %>

<div class="comment-section">
	<%= render 'review' %>
</div>
<div class="overlay" style="display:none;"></div>
	<div class="show-category-panel order-placed" style="display:none;">
		<div><span>Your order has been placed</span></div>
		<div><%= link_to "OK",product_order_index_path(:product_id=>0)%>
		</div>
	</div>
	<div id="show-all-product-type", style="display:none;">
		<div class="related-product-header">Choose recommended items for <%= @product.name %></div>
		<div class="related-product-display-section"></div>
		<div><a href="#", class="btn btn-primary link-add-related-product", id="btn_relate_product_<%= @product.id %>">Done</a><a href="#", class="btn-secondary">Close</a></div>
	</div>
<%= render "layouts/shipping_address" %>
<%= render "additional_images" %>