config/routes.rb
Rails.application.routes.draw do
  get 'product_available_areas/index'

  get 'user_accounts/show'

  get 'order/index'

  get 'admin/index'
  get 'product/autocomplete_product_name'

  get 'home/index'
devise_for :users, controllers: { registrations: "registration" }

  resources :product do
    resource :cart_items
      member do
        put :add_category
        put :check_product_for_city
        get :product_avaliability
      end
  end  

  resources :product do
    member do
      post :products_by_category
      post :create_update_related_product
      get :count_additional_images
      get :get_additional_images
    end
  resources :order
  end

resources :order do
  member do
    get :gen_order_invoice
  end
end

resources :cart do
  member do
    put :quantity_update
  end
end
  resources :admin
  resources :user_accounts
  resource :reviews
  resource :products_likes
  resources :shipping_addresses do
    member do
      put :update_selected_address
    end
  end
  
  resources :locations
  resources :pictures 
  resources :hello
  resources :conversations do
    member do
      get :notify_typing_action
    end
    resources :messages
  end

  resources :account_activations, only: [:edit]
  
  root 'product#index'
  post 'product_search' => 'product#search'
  get 'admin_orders_status' => 'order#admin_orders_status'
  post 'admin_order_search' => 'order#search'
  post 'add_product_to_cart' => 'product#addtocart'
  get  'cart_index' => 'cart#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'help' => 'home#help'
  get 'product_filter' => 'product#filter'
  get 'account_close' => 'home#accountclose'
  put 'update_order_status' => 'order#update_order_status'
  put 'remove_image_frm_dir' => 'pictures#remove_image_frm_dir'

  

  get "*path" =>  redirect('/users/sign_up') #new_user_registration_path #("/")

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		Developed by sukanta
	</small>
	<nav>
		<ul>
			<li>
				<%= link_to "About", about_path %>
			</li>
			<li>
				<%= link_to "Contacts", contact_path %>
			</li>
			<li>
				<%= link_to "Help", help_path %>
				</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse newHeader">
	<div class="container">
	<%= form_tag( product_search_path) do  %>
		<div class="product-search">
		<%= autocomplete_field_tag 'search', nil,product_autocomplete_product_name_path, placeholder: 'Search item...',class: "form-control search-query" %>
		<%= submit_tag "Search", class: "btn btn-primary" %>
		</div>
	<% end %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
			
				<li>
				<%= link_to "Home", root_path %>
				</li>

				<li> <%= link_to "Cart", cart_index_path %>
					<% if user_signed_in? && cart_counter.to_i >0 %>
						<div class="cart-counter"><%= cart_counter %></div> 
					<% end %>
					
						</li>
				<% if (user_signed_in? && current_user.isAdmin?) %>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Admin settings <b class="caret"></b>
	            		</a>
	            		<ul class="dropdown-menu">
	            			<li> <%= link_to "Add product", new_product_path, 'data-no-turbolink' => true %>
	            			</li>
	            			<li> <%= link_to "Users", admin_index_path %> </li>
	            			<li> <%= link_to "Add locations", locations_path %> </li>
	            			<li> <%= link_to "Orders management", admin_orders_status_path(:filter=>1) %> </li>
	            		</ul>
					</li>
					
				<% end %>
							
				<% if user_signed_in? %>
					
					<li class="dropdown">
						<a href="#" class="dropdown-toggle user-image" data-toggle="dropdown"> 
						<%= image_tag("users/"+(current_user.image.to_s.blank?? "user-default.png" : current_user.image.to_s),alt: current_user.fullname,title: current_user.fullname) %> 
						<b class="caret"></b>
	            		</a>
	            		<ul class="dropdown-menu">
	            			<li> <%= link_to "My account", user_account_path(current_user.id) %></li>
	            			<li> <%= link_to "Edit account", edit_user_registration_path %></li>
	            			<li> <%= link_to "My Orders", order_index_path %></li>
	            			<li> <%= link_to "Account close", user_account_path(current_user.id) , method: :delete, data: {confirm: "Are you sure to close your account?"} %></li>
	            			
	            			<li class="divider"></li>
	            			
	            			<li><%= link_to "Logout", destroy_user_session_path, method: "delete" %></li>
	            		</ul>
					</li>
				<% else %>
				
				<li>
				<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li> 
					<li>
					<%= link_to "Log in", new_user_session_path %>
					</li>
				<% end %>

			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_payment_card.html.erb
<form id="formID" method="post">
          <p>
            <%= text_field(:payee,:first_name, placeholder: "First name", class: "validate[required] form-control") %>
          </p>
          <p>
            <%= text_field(:payee,:last_name, placeholder: "Last name", class: "validate[required] form-control") %>
          </p>
          <p>
            <%= select_tag "card_type", options_for_select([["Visa", "visa"], ["MasterCard", "master"], ["Discover", "discover"], ["American Express", "american_express"]], params[:card_type]), class: "validate[required] form-control" %>
          </p>
          <p>
            <%= text_field(:payee, :card_number, placeholder: "Card number", class: "validate[required] form-control") %>
          </p>
          <p>
            <%= text_field(:payee, :card_verification, placeholder: "CVV", class: "validate[required] form-control") %>
          </p>
          <p>
            <%= date_select :date, :card_expires_on, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+15), :use_two_digit_numbers => true, class: "validate[required] form-control" %>
          </p>
        
</form>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_shipping_address.html.erb
	<!-- Modal -->
  <div class="modal fade" id="payment_modal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Payment section
          		 <a href="#", class="btn btn-primary lnk-add-new-addr" >Add new address</a>
          </h4>
         
        </div>
        <div class="modal-body" style="padding:40px 50px;">
        <div class="panel-group" id="accordion">
         <div class="panel panel-default">
	        <div id="id_address_section_toogle" class="panel-heading" > 
				<h4 class="panel-title"  data-toggle="collapse" data-parent="#accordion" data-target=".address-each-section">
			        <a class="accordion-toggle">
			          Change address
			        </a>
				</h4>
	         </div>
          <% if (user_signed_in?) %>
			<div class="address-each-section collapse", >
				<% for address in shipping_addresses %>
					<div>
						<%= radio_button_tag 'shipping_address', address.id, address.isSelected %>
						<span><%= address.address_to_ship %></span>
						<%= link_to image_tag("delete-icon.png",alt: "image",title: "remove", class: "remove-address", id: "remove_#{address.id}"),"#" %> 
						
					</div>
				<% end %>
			</div>
	<% end %>
	<div >

	<textarea id="txt_area_new_address", placeholder="Add new address", rows="6" style="display:none;"></textarea> </div>

	</div>

	<div class="panel panel-default">
	    <div id="id_address_section_toogle" class="panel-heading" > 
		    <h4 class="panel-title"  data-toggle="collapse" data-parent="#accordion" data-target="#toogle_card_details">
		        <a class="accordion-toggle">
		          Enter card details
		        </a>
			</h4>
		</div>
		<div id="toogle_card_details" >
			<div style="width: 100%; float: left; margin: 16px 0;">
				<%= render "layouts/payment_card" %>
			</div>
	        <div class="modal-footer">
		         <div class="div-check-out" style="text-align:center;">
				<% if controller_name == "cart" %>
					<a href="#", class="btn btn-primary", id="link_check_out" > Check out</a>
				<% else %>
					<a href="#", class="btn btn-primary", id="link_product_check_out" > Check out</a>
				<% end %>
					
				</div>
	        </div>
        </div>
	</div>
   </div> 
    
   </div>

  </div>

 </div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>  
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js" %>
  
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
</head>
<body>

<%= render 'layouts/header' %>
	<div class="side-menu-div">
		<ul>
		<% @product_types = product_types -%>
			<% @product_types.each do |product_type| %>
			<li><%= link_to product_type.name,product_index_path(:filter=>product_type.id) %></li>
			<% end %>
		</ul>
	</div>
	<div class="container contain-section">
	
	<%= render partial: "shared/flash_messages", flash: flash %> 
	
	<%= yield %>

	</div>
	<% if user_signed_in? %>
		<div id="users-list-for-chat">

			<div class="chat-header">Chat </div>
			<ul class="list">
			<% $users.each_with_index do |user, index| %>
			 <% if user != current_user %>    
			    <li>
			        <%= link_to user.fullname, "#", class: "btn btn-xs start-conversation",
			                    "data-sid" => current_user.id, "data-rip" => user.id %>
			      
			    </li>
			 <% end %>
			<% end %>			
			</ul>
			<input type="text", id="txt_search_user_for_chat", class="txt-chat-search-user search", placeholder="Search user" /> 
		</div>
	<% end %>
		<%= render 'layouts/footer' %>
		<div id="wait" style="display: none; width: 100%; height: 100%; position: absolute; top: 0%; padding: 2px;
		 background-color: transparent; z-index: 9999; text-align: center; "><img src='/assets/ajaxSpinner.gif' width="64" height="64" /><br>Loading..</div>
		 <audio id="chatAudio"><source src="/message_notification_tone/notification.mp3" type="audio/mp3"></audio>
</body>

</html>